# DSCI6001 1.3 Lab (Graded)

This will be a graded laboratory assignment. It should take approximately 60 minutes. If needed you can turn it in the next day.

<b>Worked with Daniel Gorham on this lab.</b>

For questions **1) - 3)**, we will work with the following matrix.   

$${\bf A} = \begin{bmatrix}
    2 & 2 & 7 \\
    3 & 4 & 1 \\
    5 & 6 & 2 \\
\end{bmatrix}$$

**1) Matrix rank**  

Use Gauss elimination to produce the row echelon form of Matrix $\mathbf{A}$. What is the rank of $\mathbf{A}$? Use [numpy.linalg.matrix_rank](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_rank.html) to check your answer.

In [40]:
# Presenting row echelon of matrix A
echelon = [[2,2,7],[0,1,-19/2],[0,0,-6]]
echelon = np.asarray(echelon)
print(echelon)

[[ 2.   2.   7. ]
 [ 0.   1.  -9.5]
 [ 0.   0.  -6. ]]


In [2]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_rank.html
import numpy as np

A = [[2,2,7], [3,4,1],[5,6,2]]

A = np.asarray(A)

np.linalg.matrix_rank(A)

3

**2) Determinant**  

Calculate the determinant of $\mathbf{A}$ by hand, then use [numpy.linalg.det](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.det.html) to check your answer.

$$2*\begin{bmatrix}
    4 & 1 \\
    6 & 2 \\
\end{bmatrix}
- 2*\begin{bmatrix}
    3 & 1 \\
    5 & 2 \\
\end{bmatrix}
+ 7*\begin{bmatrix}
    3 & 4 \\
    5 & 6 \\
\end{bmatrix}
= 2*(4*2-6*1) - 2*(3*2-5*1) + 7*(3*6-5*4) = 2*(8-6) - 2*(6-5) + 7*(18-20) = 2*2 - 2*1 + 7*2 = 12 
$$

In [31]:
# https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.det.html
np.linalg.det(A)

-11.999999999999979

**3) Matrix inversion**  

Is matrix $\mathbf{A}$ invertible? If so, use [numpy.linalg.inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) to find its inverse.

Since determinant is NOT 0, then matrix A is invertible.

In [4]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html
np.linalg.inv(A)

array([[-0.16666667, -3.16666667,  2.16666667],
       [ 0.08333333,  2.58333333, -1.58333333],
       [ 0.16666667,  0.16666667, -0.16666667]])

**4) Programming practice**  

In yesterday's lecture you were assigned to solve the following problems from the textbook:

Problem Set 7.3: 1, 3, 5, 7, 11, 13.

1. Create Numpy arrays to represent the 6 linear systems you solved by hand yesterday in Problem Set 7.3. 

2. Solve all 6 systems using Numpy. 

Extra Credit: Store your linear systems as follows: a list of the arrays of the 6 coeffiecient matrices, and a second list, of the dependent parameters (vector $\mathbf{b}$ from the notes) of each system. Zip these two lists together. Build a loop to process these arrays, built around the following code snippet. Add code to print the solutions more elegantly. Add code to handle exceptions gracefully. 

In [5]:
A1 = [[5,-2],[-1,4]]
A2 = [20.9,-19.3]
A1 = np.asarray(A1)
A2 = np.asarray(A2)
np.linalg.solve(A1,A2)

array([ 2.5, -4.2])

In [6]:
B1 = [[0.5,3.5],[-1,5]]
B2 = [5.7,7.8]
B1 = np.asarray(B1)
B2 = np.asarray(B2)
np.linalg.solve(B1,B2)

array([ 0.2,  1.6])

In [8]:
C1 = [[0.8,1.2,-0.6],[2.6,0,1.7],[4,-7.3,-1.5]]
C2 = [-7.8,15.3,1.1]
C1 = np.asarray(C1)
C2 = np.asarray(C2)
np.linalg.solve(C1,C2)

array([  8.10462808e-16,  -2.00000000e+00,   9.00000000e+00])

In [9]:
D1 = [[0,1,1],[0,4,6],[1,1,1]]
D2 = [-2,-12,2]
D1 = np.asarray(D1)
D2 = np.asarray(D2)
np.linalg.solve(D1,D2)

array([ 4.,  0., -2.])

In [28]:
E1 = [[2,-1,3],[-4,2,-6]]
E2 = [-1,2]
E1 = np.asarray(E1)
E2 = np.asarray(E2)
try:
    np.linalg.solve(E1,E2)
except:
    print('Matrices not squared. Cannot be solved.')

Matrices not squared. Cannot be solved.


In [29]:
F1 = [[0,2,1,-2],[-4,-1,-1,2],[-2,3,3,-6]]
F2 = [0,-4,-2]
F1 = np.asarray(F1)
F2 = np.asarray(F2)
try:
    np.linalg.solve(F1,F2)
except:
    print('Matrices not squared. Cannot be solved.')

Matrices not squared. Cannot be solved.


In [30]:
import numpy as np
a = [A1,B1,C1,D1,E1,F1]
b = [A2,B2,C2,D2,E2,F2]
for n, (a1, b1) in enumerate(zip(a, b)):
    
    try:
        print(n, np.linalg.solve(a1,b1))
    except:
        print(n, 'Matrices not squared. Cannot be solved.')

0 [ 2.5 -4.2]
1 [ 0.2  1.6]
2 [  8.10462808e-16  -2.00000000e+00   9.00000000e+00]
3 [ 4.  0. -2.]
4 Matrices not squared. Cannot be solved.
5 Matrices not squared. Cannot be solved.
