# RAT 7.1


1) Write the change of basis matrix M from the standard basis in $\mathbb{R}^2$ to the new basis $\{\begin{bmatrix}3\\1\end{bmatrix},\begin{bmatrix}-2\\1\end{bmatrix}\}$



2) Given the two bases
$S = \{\begin{bmatrix}2\\3\end{bmatrix},\begin{bmatrix}1\\4\end{bmatrix}\}$, $T = \{\begin{bmatrix}0\\2\end{bmatrix},\begin{bmatrix}-1\\5\end{bmatrix}\}$

and the vector $v_S = \begin{bmatrix}-2\\6\end{bmatrix}$

calculate $v_T$.


#### 1

Standard basis:

$\begin{bmatrix}1\\0\end{bmatrix}$

$\begin{bmatrix}0\\1\end{bmatrix}$

or 

$\begin{bmatrix}1&0\\0&1\end{bmatrix}$

We have:

$\begin{bmatrix}3&-2\\1&1\end{bmatrix}$


In [1]:
import numpy as np

A = np.asarray([3,-2,1,1]).reshape(2,2)
A

array([[ 3, -2],
       [ 1,  1]])

In [2]:
M = np.linalg.inv(A)
M

array([[ 0.2,  0.4],
       [-0.2,  0.6]])

#### 2

In [3]:
S = np.asarray([2,1,3,4]).reshape(2,2)
S

array([[2, 1],
       [3, 4]])

In [4]:
T = np.asarray([0,-1,2,5]).reshape(2,2)
T

array([[ 0, -1],
       [ 2,  5]])

In [5]:
v_s = np.asarray([-2,6]).reshape(2,1)
v_s

array([[-2],
       [ 6]])

In [10]:
T_inv = np.linalg.inv(T)
T_inv

array([[ 2.5,  0.5],
       [-1. , -0. ]])

In [11]:
v_t = T_inv.dot(S.dot(v_s))
v_t

array([[ 14.],
       [ -2.]])