# DSCI 6001 - 2.3: A Review of Basic Linear Algebra


### By the End Of This Lecture, you Will Be Able To:

1. Identify the key areas of knowledge required for your first test


## Vector and Matrix Rules

It's best to think of vectors and matrices as being directly related. One way of thinking about it is considering a vector to be essentially a single-row matrix. Column vectors can be then compared to columns of a matrix and row vectors can be compared to rows.

### Additive Rules of Matrices

For three matrices $\textit{A}$, $\textit{B}$, and $\textit{C}$ we have the following properties

1. Commutative Law of Addition: $\textit{A} + \textit{B} = \textit{B} + \textit{A}$

2. Associative Law of Addition: $(\textit{A} + \textit{B}) + \textit{C} = \textit{A} + (\textit{B} + \textit{C})$

3. Associative Law of Multiplication: $\textit{A}(\textit{B}\textit{C}) = (\textit{A}\textit{B})\textit{C}$

4. Distributive Law: $\textit{A}(\textit{B} + \textit{C}) = \textit{A}\textit{B} + \textit{A}\textit{C}$

5. Identity: There is the matrix equivalent of one. We define a matrix $\textit{I_n}$ of dimension  $n \times n$ such that the elements of $\textit{I_n}$ are all zero, except the diagonal elements $i=j$; where $i_{ii} = 1$

6. Zero: We define a matrix 0 of $m \times n$ dimension as the matrix where all components $ij$ are 0

Therefore,

$I_3 = \begin{bmatrix}
    1 & 0 & 0\\
    0 & 1 & 0 \\
    0 & 0 & 1\\
\end{bmatrix}$

Here we can write $\textit{I}\textit{B} = \textit{B}\textit{I} = \textit{B}$ or 

$\textit{I}\textit{I} = \textit{I}$

### Matrix Transpose

The **transpose** of a matrix $\textit{A}$ is formed by *interchanging* the rows and columns of $\textit{A}$. That is 

$a_{ij}^T = a_{ji}$

### Vector Multiplication

Vectors have several ways they can be multiplied. In this program, we normally think of vectors as single-row or single-column matrices. Very frequently, we will see column vectors used with matrices. 

If we have two vectors:

${\bf{x}} = (x_1, x_2, ... , x_k)$ and ${\bf{y}} = (y_1,y_2,...,y_k)$

The inner product is written:

$${\bf{x}} \cdot {\bf{y}} = x_{1}y_{1}+x_{2}y_{2}+\cdots+x_{k}y_{k}$$

Therefore this produces a single *scalar* value.

Following suit with the vectors-as-matrices trope, we can also write:

${\bf{x}} \cdot {\bf{y}} = {\bf{x}^{T}}{\bf{y}}$ =

$ \begin{bmatrix}x_1 & x_2 & \cdots & x_k\end{bmatrix} \begin{bmatrix}y_1 \\ y_2 \\ \vdots \\ y_k\end{bmatrix}$



### Matrix Multiplication

When two matrices $\bf{A}$ and $\bf{B}$ are multiplied together we can write the product $\bf{C}$ in *closed form* 

$\bf{C} = \bf{A}\bf{B}$, whose elements $c_{ij}$ are given by addition of each component of the two matrices,  $c_{ij} = \sum_{k=1}a_{ik}b_{kj}$. When done by hand, this process is performed like a vector dot product, multiplying each element in the left matrix's row $i$ by the right matrix's column $j$ and summing. This product becomes the entry $c_{ij}$.

#### Example:

$$\begin{bmatrix}
    5 & -3 \\
    0 & -4 \\
\end{bmatrix} \begin{bmatrix}
    -2 & 0 \\
    5 & 6 \\
\end{bmatrix} = \begin{bmatrix}
    -25 & -18 \\
    -20 & -24 \\
\end{bmatrix}$$

Matrix multiplication is **not commutative**, that is

$$\begin{bmatrix}
    -2 & 0 \\
    5 & 6 \\
\end{bmatrix} \begin{bmatrix}
    5 & -3 \\
    0 & -4 \\
\end{bmatrix} = \begin{bmatrix}
    -10 & 6 \\
    25 & -39 \\
\end{bmatrix}$$

Remember: if you've a computer handy, you can always check your results with numpy:

In [2]:
import numpy as np
A = np.asarray([[-2,0],[5,6]])
B = np.asarray([[5,-3],[0,-4]])
print A.dot(B)
print B.dot(A)

[[-10   6]
 [ 25 -39]]
[[-25 -18]
 [-20 -24]]


### QUIZ: 
Write a matrix multiplication function of any size using for loops in Python:

`def matrix_multiply(A, B):
    #check to see if A and B are both np arrays
    # check that the dimensions of each matrix are compatible
    # you need to create C
    for row in enumerate(A):
        for column in enumerate(B.T):
            #something goes here
    return C`

In [45]:
import numpy as np
def matrix_multiply(A, B):
    if isinstance(A, np.ndarray) == False or isinstance(B, np.ndarray) == False:
        print("Both matrices must be numpy arrays.")
    else:
        if A.shape != B.shape:
            print("Both matrices must have the same dimensions.")
        else:
            C = []
            for row in enumerate(A):
                for column in enumerate(B.T):
                    # row and column are tuples because we use enumerate, so 
                    # we need to select by index (get the data we need).
                    C.append(row[1].dot(column[1]))
                    
            C = np.asarray(C)
            C = C.reshape(A.shape[0], A.shape[0])
                
            return C

In [49]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]

A = np.asarray(A)
B = np.asarray(B)

matrix_multiply(A,B)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

### More Properties of Matrix Multiplication

These are listed in the book on pp. 321:

1. Matrix multiplication is not commutative (you know this), thus ${\bf{AB}} \neq {\bf{BA}}$.
2. ${\bf{AB}} = 0$ does **not** imply ${\bf{A}}=0$, ${\bf{B}}=0$ or ${\bf{BA}}=0$ !!! **EXCEPTION:** When ${\bf{A}}$, ${\bf{B}}$, ${\bf{C}}$ are $n \times n$ matrices (square) **and** $rank\ {\bf{A}}=n$, then it is implied ${\bf{B}}=0$.
3. ${\bf{AC}}={\bf{AD}}$ does **not** imply ${\bf{C}}={\bf{D}}$. **EXCEPTION:** When ${\bf{A}}$, ${\bf{B}}$, ${\bf{C}}$ are $n \times n$ matrices (square) **and** $rank\ {\bf{A}}=n$ (square, linearly independent, invertible).
4. When ${\bf{A}}$ is singular (noninvertible, zero determinant), then so are ${\bf{AB}}$ and ${\bf{BA}}$.

##Vector Spaces

Recall the following vector space properties:

   1. Closure under addition:  
       $$\text{If }{\bf x},{\bf y} \in V, \text{ then } {\bf x} + {\bf y} \in V$$

   2. Commutativity of vector addition:
       $${\bf x}+{\bf y} = {\bf y} + {\bf x}$$

   3. Associativity of vector addition:
       $${\bf x}+({\bf y}+{\bf z})=({\bf x}+{\bf y})+{\bf z}$$
       
   4. Additive identity
       $${\bf 0}+{\bf x} = {\bf x} + {\bf 0} = {\bf x}$$
       
   5. Existence of additive inverse
       $${\bf x} + (- {\bf x}) = {\bf 0}$$
       
   6. Closure under scalar multiplication
       $$\text{for any scalar }a \text{ and } {\bf x}\in V, a{\bf x}\in V$$ 
       
   5. Associativity of scalar multiplication
       $$a(b {\bf x})=(ab){\bf x}$$

   6. Distributivity of scalar sums
       $$(a+b){\bf x} = a{\bf x} + b {\bf x}$$

   7. Distributivity of vector sums
       $$a({\bf x} + {\bf y})=a{\bf x}+a {\bf y}$$

   8. Scalar multiplication identity
       $$1 {\bf x} = {\bf x}$$
       
Although this seems like a lot to remember, the important thing is to realize that they function as a coherent set of rules to follow when dealing with vectors. They also reduce the notion of arrays of numbers into small symbols that can be coherently talked about in **closed form**.

###QUIZ:

What is the most commonly used vector space? Why do we prefer it over all others?

##Linear Independence

The previous discussion of linear independence leads us to a discussion of what it is. A set of vectors is **linearly independent** iff each vector cannot be constructed as a combination of the other vectors. Thus, each vector is *independent* from each other. 

The premier way to determine linear independence and thus the **rank** and **nullity** of a matrix is by performing Gauss elimination and back substitution.

Another way to determine linear independence is by obtaining the **determinant** of the matrix.


## Rank, Span

An idea integral to understanding vector spaces is the notion of a  *spanning set*. The basic concept is that we create a basis set of vectors that is capable of reproducing any other vector (and thus reaching every point) within a given vector space $V$. 

The best example of this is the standard basis set of dimension $n$,  $e_{n}$. This basis set is capable of reproducing any other point in $R^{n}$. 

Now that you know more about linear algebra, we can talk a bit about how to get a span and what takes place with it. 

Suppose we have a transformation $L$ in $R^3$:

${\bf{L}} = \begin{bmatrix}1 & 0 & -1\\2 & 2 & -1 \\ 3 & 0 & -3 \end{bmatrix}$

The **span** of the transformation is obtained by determining the linearly independent vectors of it, such that we form a *basis*.

First, produce the reduced row-eschelon form of the transformation so you can see its **rank**:

${\bf{L}} = \begin{bmatrix}1 & 0 & -1\\0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

### QUIZ:
What is the rank of $L$?


Clearly, the system is not *Linearly Independent*. The entire space of the transformation can be *spanned* by two vectors:

$span\ L = c_{1}\begin{bmatrix}1 \\ 0 \\ -1\end{bmatrix} + c_{2}\begin{bmatrix}0 \\ 1 \\ 0\end{bmatrix}$


You could go back and see that $L_{1}$ is $\begin{bmatrix}1 \\ 0 \\ -1\end{bmatrix}$ and $L_{3}$ is $\begin{bmatrix}3 \\ 0 \\ -3\end{bmatrix} = 3\begin{bmatrix}1 \\ 0 \\ -1\end{bmatrix}$


The **range** or **image** of this transformation is the set of column vectors spanned by it, as if it were ${\bf{Lx}}$:

$image\ L = x_{1}\begin{bmatrix} 1 \\2 \\ 3 \end{bmatrix} +  x_{2}\begin{bmatrix} 1 \\2 \\ 3 \end{bmatrix} +  x_{3}\begin{bmatrix} 1 \\2 \\ 3 \end{bmatrix}$

Thus the image denotes all possible values the transformation could take, admitting any possible value of $\bf x$

### QUIZ:

This leads us to another very important topic. How do we know that a set is a spanning set of a vector space $V$? 

## The Inverse of a Matrix

Getting the inverse of a matrix is very important, because much of the processes used in linear algebra, particularly the design of equations to compute a needed value, is based on matrix invertibility.


### The shared relationship of linear independence
There is a shared relationship amongst determinants, inverses, and linear independence.
1. If a matrix has a nonzero determinant, the linear system it characterizes has a determined solution.
2. If a transformation is invertible, its matrix will have a nonzero determinant.
3. If a transformation spans its vector space, its span is linearly independent and has the same rank as the vector space's dimension.

### QUIZ:
How do you know if a matrix is invertible? What's the fastest way to get that information?


### Obtaining the Inverse
The inverse of an invertible matrix should be obtainable by one of at least two methods (although there are more):

1. Gauss-Jordan elimination.
2. The general inverse method (inverse by cofactors)

###QUIZ:
Compute the inverse of $\begin{bmatrix}2&6\\-2&1\end{bmatrix}$ using both methods.


##Solving the Eigenproblem

The eigenproblem:

$${\bf A}{\bf x} = \lambda {\bf x}$$

is of tremendous importance. Sometimes you will see it posed as the "general eigenproblem," which differs little from the standard formulation:

$${\bf A}{\bf x} = {\bf B}\lambda {\bf x}$$

If ${\bf B}$ is invertible this is exactly the same as the standard formulation.

###QUIZ:
Why do we say this here?

-----

You are responsible for being able to describe all features of the figure featured in lecture 2.2 in your own words. (reviewed in class)

We typically solve the eigenproblem through the use of the **characteristic polynomial**, which is derived from posing the standard eigenproblem as an equation solved for $\bf 0$ and computing its determinant:

$$\left|{\bf A}-\lambda\right|{\bf x}={\bf 0}$$

This is interesting. Why the use of a determinant here? We are producing a model wherein the hypothesis is that we are trying to find vectors **other than 0** that satisfy $({\bf A}-\lambda){\bf x}={\bf 0}$. This means that the hypothesized matrix $({\bf A}-\lambda)$ is **not** invertible. Hence, it must have a determinant of **0**.

###QUIZ:
Why does the characteristic equation require $({\bf A}-\lambda)$ to be singular?



##To Solve in Class:


Given A = $\begin{bmatrix}1 & 2 & -8 \\ 2 & 4 & 10 \\ 3 & 1 & 2 \\ 0 & 2 & 4 \end{bmatrix}$
and B = $\begin{bmatrix} 2 & 0 & 1 & 1 \\ 4 & 1 & 2 & 0\\ 0 & 2 & 3 & 4\end{bmatrix}$

1. Does A have a determinant? Does B have a determinant? Are they invertible?
2. Can we compute $\bf{AB}$ What would this product be?
3. Does $\bf{AB^{-1}}$ exist?
4. If $\bf{AB}$ exists, does $\bf{AB}^{T}$?
5. $\bf{AB}^{-1}$ what would this be in both closed and open form?
6. What are the eigenvalues of $\bf{BA}$?