# RAT 5.4

1. Describe in your own words what an orthogonal matrix is in terms of its action on other matrices or vectors. In what ways do we obtain an orthogonal matrix?

2. Assume $D$ is orthogonal. What is its determinant?

3. What is the transpose of $A=\begin{bmatrix}1 & 3 & -1\\2 & -1 & -2\\4 & 1& -1\end{bmatrix}$? What is the closed formula for the transpose of a matrix?

4. What is a symmetric matrix? What is the closed formula for the transpose of a symmetric matrix?

5. Identify the image and kernel of $A = \begin{bmatrix}1 & 3 & -1\\2 & 7 & -2\\3 & 9& -3\end{bmatrix}$

6. Take two vectors $v_1 = \begin{bmatrix}1 \\ -1 \\ -3\end{bmatrix}$, $v_2 = \begin{bmatrix}3 \\ -2 \\ 1\end{bmatrix}$. Are these two vectors normal to each other? Produce a calculation that shows this. Use the Gram-Schmidt method to make them *orthonormal* to each other. Now do they form a basis for $\mathbb{R}^2$?

### 1

We use Graham-Schmidt to obtain an ortoghonal matrix. If Q is orthogonal:

$Q^TQ = I$

### 2
The sum of it's diagonal elements.

### 3
$A=\begin{bmatrix}1 & 3 & -1\\2 & -1 & -2\\4 & 1& -1\end{bmatrix}$

$A^T=\begin{bmatrix}1 & 2 & 4\\3 & -1 & 1\\-1 & -2& -1\end{bmatrix}$

### 4
Example of symmetric matrix:

$A=\begin{bmatrix}0 & 1 & 3\\1 & 0 & 2\\3 & 2& 0\end{bmatrix}$

### 5
Column 3 is column 1 times (-1), so it's dependent on column 1.

The columns that are linearly independent are 1 and 2. So the image is:

$\begin{bmatrix}1\\2\\3\end{bmatrix}, \begin{bmatrix}3\\7\\9\end{bmatrix}$

$\begin{bmatrix}1 & 3 & -1\\2 & 7 & -2\\3 & 9& -3\end{bmatrix}$

Row 3 = Row 3/3:

$\begin{bmatrix}1 & 3 & -1\\2 & 7 & -2\\1 & 3& -1\end{bmatrix}$

Row 3 = 2 * Row 3 - Row 2:

$\begin{bmatrix}1 & 3 & -1\\2 & 7 & -2\\0 &-1& 0\end{bmatrix}$

Row 2 = Row 2 - 2 * Row 1:

$\begin{bmatrix}1 & 3 & -1\\0 & 1 & 0\\0 &-1& 0\end{bmatrix}$

If y = t, x + 3y - z = 0, 

### 6

In [1]:
import numpy as np

v_1 = np.asarray([1,-1,-3])
v_2 = np.asarray([3,-2,1])

v_1 = v_1.reshape(3,1)
v_2 = v_2.reshape(3,1)

In [2]:
v_1.T.dot(v_2)

array([[2]])

Since the dot product is not 0, they are not normal to each other.

In [3]:
u_1 = v_1/np.linalg.norm(v_1)

In [4]:
# First orthonormal vector normalized:
u_1

array([[ 0.30151134],
       [-0.30151134],
       [-0.90453403]])

In [5]:
u_2 = v_2 - (u_1.T.dot(v_2)/v_2.T.dot(v_2)) * v_2

In [8]:
# Second orthonormal vector:
u_2
u_2 = u_2/np.linalg.norm(u_2)
u_2

array([[ 0.80178373],
       [-0.53452248],
       [ 0.26726124]])