# RAT 6.1

1. Factor these two vectors to their simplest representation:
   
    $v_1 = \begin{bmatrix}15\\-25\\-5\end{bmatrix}$
    
    $v_2 = \begin{bmatrix}-3\sqrt{15}\\15\sqrt{5}\\-9\sqrt{20}\end{bmatrix}$
    
2. Calculate the inner product of $v_1$ and $v_2$, $v_1^{T}v_2$

3. Make a short list of 5-10 elementary functions

4. What is the formal (equation) definition of the derivative? What does it describe?

5. Calculate the limit derivative of $f(x) = x^{2}$. Show all steps.

6. What is the second whole derivative with respect to x of $f(x) = sin^{2}(x)$? Show all steps and use the chain rule.



In [9]:
import numpy as np

### 1

In [10]:
v1 = np.asarray([15,-25,-5])
v1 = v1.reshape(3,1)
v1

array([[ 15],
       [-25],
       [ -5]])

In [11]:
v2 = np.asarray([-3*(15)**0.5,15*(5)**0.5,-9*(20)**0.5])
v2 = v1.reshape(3,1)
v2

array([[ 15],
       [-25],
       [ -5]])

In [12]:
v1 = v1/5
v1

array([[ 3.],
       [-5.],
       [-1.]])

In [13]:
v2 = v2/5
v2

array([[ 3.],
       [-5.],
       [-1.]])

### 2

In [14]:
v1.T.dot(v2)

array([[ 35.]])

### 3

f(x) = x

f(x) = $x^2$

f(x) = 2x + 1

f(x) = $e^x$

f(x) = $x^2$ - 2x

f(x) = 1/x

### 4

It's the limit when $\triangle x$ = 0

(f(x + $\triangle x$) - f(x))/$\triangle x$

It represents the slope of the tangent and $\triangle x$.

### 5

f(x) = $x^2$

(($x + \triangle x)^2 - x^2)/\triangle x$ = ($x^2 + 2x\triangle x + (\triangle x)^2) - x^2/\triangle x$ = ($2x\triangle x + (\triangle x)^2)/\triangle x$

### 6

$f(x) = sin(x)^ 2$

$f'(x) = 2 * sin(x) * cos(x)$

$f''(x) = 2 * ((cos(x) * cos(x) - sin(x) * sin(x))) = 2 * (cos(x)^2 - sin(x)^2)$