# DSCI 6001 5.3 Lab 

## QR Factorization II


## Practical application of the QR algorithm: Stabilized Gram-Schmidt 


Because the GS mapping is so onerous (and numerically unstable) to calculate, and the results so difficult to compare,
there are several ways in which this problem is addressed. The first is by creating the **Modified or Stabilized Gram Schmidt** algorithm, which creates a different Gram-Schmidt factorization (usually in-place) by using normalized vectors as the input in all parts of the computation, making numerical errors much smaller by comparison:

#### Modified Gram-Schmidt


$for\ j\ in\ \{1 \cdots k\}$

  $\ \ \ \ \ for\ i\ in\ \{1 \cdots j-1\}$
  
   $\ \ \ \ \ \ \ \  v_j = v_j - \text{proj}_{v_{i}}v_{j}$
   
   $\ \ \ \ \   v_j = v_{j}/\|v_{j}\|$
            

### TASK:

Implement the MGS algorithm using the below code stub.


In [ ]:
def stabilized_gram_schmidt(a):
        print(a)
        # * I recommend getting the number of columns (or rows if you prefer to flip the matrix)
        # * make sure your matrix A is cast into floats
        # * begin the top for loop
                #* begin the bottom for loop
                        # * use the projection subtraction here:
                        # remove projection of a[j] over a[i] from a[j]
                # * normalize the column (or row) you're working through
                
        pass # * return the matrix here. don't rely on pass-by-reference

In [35]:
import numpy as np
def stabilized_gram_schmidt(a):
    # Transposing original matrix and casting to float.
    A = a.T.astype(float)
    
    # We iterate through rows as we transposed the original matrix.
    for i in range(A.shape[0]):
        # First row is 0, so the range for the 2nd loop, which loops through each row element (it's column location) 
        # end at i, not i-1.
        for j in range(i):
            # Calculating row projection.
            A[i] = A[i] - (A[i].dot(A[j])/A[j].dot(A[j]))* A[j]
        
        # Normalizing row projection.
        A[i] = A[i]/np.linalg.norm(A[i])
       
    # We need to return the transpose of the result.
    return A.T

In [36]:
# Quick test harness

A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])
Q = stabilized_gram_schmidt(A)
R = Q.dot(A)

R = Q.T.dot(A)
print(Q)
print(Q.dot(R))

[[-0.81649658 -0.53452248 -0.21821789]
 [ 0.40824829 -0.80178373  0.43643578]
 [ 0.40824829 -0.26726124 -0.87287156]]
[[ -2.00000000e+00  -2.90724631e-16   1.00000000e+00]
 [  1.00000000e+00  -2.00000000e+00   1.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00   6.24796589e-16]]
