# DSCI 6001 - 3.3 Lab: LU Factorization II

Today we are going to code up the algorithm that you wrote down yesterday using the scaffold provided below. Simply follow the prompts. 

You might find [this](http://nucinkis-lab.cc.ic.ac.uk/HELM/workbooks/workbook_30/30_3_lu_decomposition.pdf) helpful for reviewing LU decomposition.


In [1]:
import numpy as np
import pprint

def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    """C = AB - also recall the matrix multiplication formula"""
    C = M.dot(N)
    
    return C

In [2]:
def pivot_matrix(M):
    """Returns the pivoting matrix P for M, as used in Doolittle's method."""
    m = len(M)

    # *Create an identity matrix, with floating point values. You may use numpy
    
    # id_mat = ?
    
    id_mat = [[float(i==j) for i in range(m)] for j in range(m)]

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M
    
    # for every row in the input matrix
    for j in range(m):
        # *find the row with the biggest element in column j (so we are looking for the diagonal elements M[j,j])
        # *we do not want to be swapping with rows above this one, just the rows below it.
        
        # Get the index of the column. We transpose M column to a row to make it feasible.
        # Line below does not provide consistent results.
        #row = max(range(j,m), key=lambda i: abs(M[i][j]))
        row = np.argmax(M, axis=0)[j]
        
        if j != row: #if this row is not the row with the next biggest diagonal element
            
            # *Swap the rows of the id matrix
            id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

    return np.asarray(id_mat)

## Useful formulas below

$u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$

$l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$

In [6]:
def LU_decompose(PA, L, U, n):
    """Performs the actual LU decomposition using the standard formula"""
    
    for j in range(n):
        
        # All diagonal entries of L are first set to 1, you may use numpy to do this as well. 
        np.fill_diagonal(L, 1)

        # *Encode the following logic:
        # *LaTeX: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$                                                                                                                                                                                     
        for i in range(j+1):
            partial_sum = 0
            
            #for k in range(i-1):
            #U[0] = A[0]
            for k in range(i):
                partial_sum += U[k,j] * L[i,k]
                #U[k] = PA[k] - dot(L[k,0:k],U[0:k])
            
            U[i,j] = PA[i,j] - partial_sum
                  
        # *Encode the following logic:
        # *LaTeX: $l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$                                                                                                                                                                  
        for i in range(j, n):
            partial_sum = 0
            
            for k in range(j):
                partial_sum += U[k,j] * L[i,k]
            
            L[i,j] = (PA[i,j] - partial_sum)/U[j,j]
        
    return L, U

In [7]:
def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # * Create zero matrices for L and U or use np.zeros(())                                                                                                                                                                                                                
    # L = ?
    # U = ?
    L = np.zeros((n,n))
    U = np.zeros((n,n))

    # Create the pivot matrix P and the matrix product PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)
    # Decompose
    L, U = LU_decompose(PA, L, U, n)
    
    return (P, L, U)

In [8]:
A = [[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]]
A = np.asarray(A)

P, L, U = lu_decomposition(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
P:
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
U:
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])
