# DSCI 6001 - 3.3 Lab: LU Factorization II

Today we are going to code up the algorithm that you wrote down yesterday using the scaffold provided below. Simply follow the prompts. 

You might find [this](http://nucinkis-lab.cc.ic.ac.uk/HELM/workbooks/workbook_30/30_3_lu_decomposition.pdf) helpful for reviewing LU decomposition.


In [1]:
import numpy as np
import pprint

def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    """C = AB - also recall the matrix multiplication formula"""
    C = M.dot(N)
    
    return C

In [2]:
def pivot_matrix(M):
    """Returns the pivoting matrix P for M, as used in Doolittle's method."""
    m = len(M)

    # *Create an identity matrix, with floating point values. You may use numpy
    
    # id_mat = ?
    
    id_mat = np.identity(m)

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M
    
    # for every row in the input matrix
    for j in range(m):
        # *find the row with the biggest element in column j (so we are looking for the diagonal elements M[j,j])
        # *we do not want to be swapping with rows above this one, just the rows below it.
        
        # Get the index of the column. We transpose M column to a row to make it feasible.
        row = np.argmax(M.T[j])
        
        if j != row: #if this row is not the row with the next biggest diagonal element
            
            # *Swap the rows of the id matrix
            id_mat[[row,j]] = id_mat[[j, row]]

    return id_mat

## Useful formulas below

$u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$

$l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$

In [3]:
def LU_decompose(PA, L, U, n):
    """Performs the actual LU decomposition using the standard formula"""
    
    for j in range(n):
        
        # All diagonal entries of L are first set to 1, you may use numpy to do this as well. 
        np.fill_diagonal(L, 1)

        # *Encode the following logic:
        # *LaTeX: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$                                                                                                                                                                                     
        for i in range(j+1):
            partial_sum = 0
            
            for k in range(i-1):
                partial_sum += U[[k,j]] * L[[i,k]]
            
            U[[i,j]] = PA[[i,j]] - partial_sum
                  
        # *Encode the following logic:
        # *LaTeX: $l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$                                                                                                                                                                  
        for i in range(j, n):
            partial_sum = 0
            
            for k in range(j-1):
                partial_sum += U[[k,j]] * L[[i,k]]
            
            L[[i,j]] = (PA[[i,j]] - partial_sum)/U[[j,j]]
        
    return L, U

In [ ]:
def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k) != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
            a[i,k] = lam
    return a

In [4]:
def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # * Create zero matrices for L and U or use np.zeros(())                                                                                                                                                                                                                
    # L = ?
    # U = ?
    L = np.zeros((n,n))
    U = np.zeros((n,n))

    # Create the pivot matrix P and the matrix product PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)
    # Decompose
    L, U = LU_decompose(PA, L, U, n)
    
    return (P, L, U)

In [5]:
A = [[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]]
A = np.asarray(A)
pivot_matrix(A)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [6]:
A = [[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]]
A = np.asarray(A)

P, L, U = lu_decomposition(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
P:
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
L:
array([[  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [-inf,  inf,   1., -inf],
       [ -1.,  -1.,  -1.,  -1.]])
U:
array([[  7.,   3.,  -1.,   2.],
       [  3.,   8.,   1.,  -4.],
       [ inf, -inf,   5.,  inf],
       [  2.,  -4.,  -1.,   6.]])


//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:27: RuntimeWarning: divide by zero encountered in true_divide
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:15: RuntimeWarning: invalid value encountered in add
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:25: RuntimeWarning: invalid value encountered in add
