### DSCI6001 2.1 Lab

This will be a graded laboratory assignment of approximately 30 minutes.

Review [numpy.linalg.solve](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html). 

1. Create matrices representing the linear systems in Kreyszig Chapter 7 (9th ed. page 330) problems 12, 14, 16, 18.
      
2. Confirm the shapes of the coefficient matrices, by inspection or using Python. Which of these can numpy solve? Use numpy to solve the systems it can solve. Explain the solution set to the systems numpy cannot solve.
   
3. Create numpy  matrices A and B, and vectors a, b from Kreyszig Chapter 7 (9th ed. page 331). Using Python, calculate:
    * AB, BA
    * $\textit{A}\textit{A}^{T}$
    * $\textit{B}^{T}\textit{A}$
    * $\textit{a}^{T}\textit{b}$
    * $\textit{b}^{T}\textit{a}$
    * $\textit{ab}^{T}$    
    * $\textit0.1({A}+{A}^{T})({B}-{B}^{T})$

4. According to the [Pew Research Center](http://www.pewsocialtrends.org/2015/12/09/the-american-middle-class-is-losing-ground/), America in 1970 was 10% lower, 62% middle, and 28% upper class. Create a simple Markov process to model the decades from 1970 to 2070, using the following estimates that per decade... 
* Lower class has a 5% chance of becoming middle class, 1% of upper class
* Middle class has a 10% chance of lower class, and a 5% chance upper class
* Upper class: 5% chance become lower class, 10% become middle class

In [10]:
import numpy as np

A = np.asarray([[-2,-4,7],[1,2,16]])
B = np.asarray([-6,3])
C = np.asarray([[5,-10], [3,1],[-1,6]])
D = np.asarray([2,13,6])
E = np.asarray([[0,2,1],[2,3,-1],[5,-4,3]])
F = np.asarray([-1,-12,32])
G = np.asarray([[-1,4,-2],[3,4,6],[1,-2,2]])
H = np.asarray([1,1,-1/2])

In [11]:
A.shape, B.shape, C.shape, D.shape, E.shape, F.shape, G.shape, H.shape

((2, 3), (2,), (3, 2), (3,), (3, 3), (3,), (3, 3), (3,))

In [12]:
A_coeff = [A,C,E,G]
B_param = [B,D,F,H]

def solve_linear(A,B):
    for a,b in zip(A_coeff, B_param):
        try:
            print(np.linalg.solve(a,b))
        except:
            print('Cannot solve linear system.')

In [13]:
solve_linear(A_coff,B_param)

Cannot solve linear system.
Cannot solve linear system.
[ 1. -3.  5.]
[-0.5   0.25  0.25]


The systems that cannot be solved is because the number of columns of the coefficient matrix does not match the number of rows of the dependent vector.

In [15]:
A1 = np.asarray([[9,2,8],[2,18,10],[8,10,15]])
B1 = np.asarray([[0,2,6],[-2,0,-3],[-6,3,0]])
a1 = np.asarray([[3],[7],[1]])
b1 = np.asarray([[4],[0],[2]])

In [18]:
# AB, BA
A1.dot(B1), B1.dot(A1)

(array([[ -52,   42,   48],
        [ -96,   34,  -42],
        [-110,   61,   18]]), array([[ 52,  96, 110],
        [-42, -34, -61],
        [-48,  42, -18]]))

In [20]:
A1.dot(A1.T)

array([[149, 134, 212],
       [134, 428, 346],
       [212, 346, 389]])

In [22]:
B1.T.dot(A1)

array([[ -52,  -96, -110],
       [  42,   34,   61],
       [  48,  -42,   18]])

In [24]:
a1.T.dot(b1)

array([[14]])

In [25]:
b1.T.dot(a1)

array([[14]])

In [26]:
a1.dot(b1.T)

array([[12,  0,  6],
       [28,  0, 14],
       [ 4,  0,  2]])

In [28]:
0.1 * (np.add(A1,A1.T).dot(np.add(B1,np.multiply(B1,-1).T)))

array([[-20.8,  16.8,  19.2],
       [-38.4,  13.6, -16.8],
       [-44. ,  24.4,   7.2]])

In [38]:
# Markow process.
probs = [[0.1],[0.62],[0.28]]
row_labels = ['low','middle','upper']
column_labels = ['low','middle','upper']
# The probability of low staying low is: 1 - 0.05 -0.01 (outflows) = 0.94
# The probability of middle staying middle is: 1 - 0.05 -0.1 (outflows) = 0.85
# The probability of upper staying upper is: 1 - 0.05 - 0.1 (outflows) = 0.85

M = np.asarray([[.94,0.05,0.01],[0.1,0.85,0.05],[0.05,0.1,0.85]])

In [41]:
# 1970 => 0, 1980 => 1, 1990 => 2, 2000 => 3, 2010 => 4, 2020 => 5, 2030 => 6, 2040 => 7, 2050 => 8, 
# 2060 => 9, 2070 => 10
# Decades go from a range from 0 to 10.
# We start at item 1 of the range since we want to start calculating at 1980, not 1970.
for i in range(1,11):
    print(np.linalg.matrix_power(M.T,i).dot(probs))

[[ 0.17]
 [ 0.56]
 [ 0.27]]
[[ 0.2293]
 [ 0.5115]
 [ 0.2592]]
[[ 0.279652]
 [ 0.47216 ]
 [ 0.248188]]
[[ 0.32249828]
 [ 0.4401374 ]
 [ 0.23736432]]
[[ 0.35903034]
 [ 0.41397814]
 [ 0.22699152]]
[[ 0.39023591]
 [ 0.39253209]
 [ 0.21723201]]
[[ 0.41693656]
 [ 0.37488727]
 [ 0.20817617]]
[[ 0.4398179 ]
 [ 0.36031862]
 [ 0.19986347]]
[[ 0.45945387]
 [ 0.34824807]
 [ 0.19229806]]
[[ 0.47632634]
 [ 0.33821336]
 [ 0.18546029]]
