## Linear Transformations Examples

Find the matrix A in the indicated linear transformation y = Ax.

#1. Reflection about the y-axis in $R^2$.

In [10]:
import numpy as np

A = np.asarray([[-1,0],[0,1]])
A

array([[-1,  0],
       [ 0,  1]])

Reflection about the y-axis in $R^2$ means that the x coordinate changes sign, while y coordinate stays the same. It's like looking a mirror.

In [7]:
# Example.
a = np.asarray([[3],[2]])
print("Original vector", a)
print("Transformed vector", A.dot(a))

Original vector [[3]
 [2]]
Transformed vector [[-3]
 [ 2]]


#2. Reflection about the xy-plane in $R^3$.

In [8]:
B = np.asarray([[1,0,0],[0,1,0],[0,0,-1]])
B

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [9]:
# Example.
b = np.asarray([[3],[2],[1]])
print("Original vector", b)
print("Transformed vector", B.dot(b))

Original vector [[3]
 [2]
 [1]]
Transformed vector [[ 3]
 [ 2]
 [-1]]


#3. Orthogonal projection (perpendicular projection) of $R^2$ onto the x-axis.

Projection means we lose one dimension, in the case above, we lose the y axis information.

In [11]:
C = np.asarray([[1,0],[0,0]])
C

array([[1, 0],
       [0, 0]])

In [12]:
# Example.
c = np.asarray([[3],[2]])
print("Original vector", c)
print("Transformed vector", C.dot(c))

Original vector [[3]
 [2]]
Transformed vector [[3]
 [0]]


#4. Orthogonal projection of $R^3$ onto the plane y = x.

We lose the information of z axis.

In [13]:
D = np.asarray([[1,0,0],[0,1,0],[0,0,0]])
D

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [14]:
# Example.
d = np.asarray([[3],[2],[7]])
print("Original vector", d)
print("Transformed vector", D.dot(d))

Original vector [[3]
 [2]
 [7]]
Transformed vector [[3]
 [2]
 [0]]


#5. Dilatation (uniform stretching) in $R^2$ by a factor S.

In [15]:
k = 5
# Example.
e = np.asarray([[3],[2],[7]])
print("Original vector", e)
print("Transformed vector", k*e)

Original vector [[3]
 [2]
 [7]]
Transformed vector [[15]
 [10]
 [35]]


#6. Counterclockwise rotation through the angle $\pi/2$ about the origin in $R^2$.

The general transformation matrix is:

${\bf E} = \left[ \begin{matrix} \cos{\theta} & -\sin{\theta} \\ \sin{\theta} & \cos{\theta} \end{matrix} \right]$

The transformation matrix for $\theta = \pi/2$ is:

${\bf E} = \left[ \begin{matrix} \cos{\pi/2} & -\sin{\pi/2} \\ \sin{\pi/2} & \cos{\pi/2} \end{matrix} \right]$

${\bf E} = \left[ \begin{matrix} 0 & -1 \\ 1 & 0 \end{matrix} \right]$

In [16]:
# Example.
E = np.asarray([[0,-1],[1,0]])
f = np.asarray([[3],[2]])
print("Original vector", f)
print("Transformed vector", E.dot(f))

Original vector [[3]
 [2]]
Transformed vector [[-2]
 [ 3]]
