# RAT 4.1

1. Describe the three component matrices of an SVD.
2. What special properties do the three component matrices have?
3. Use numpy (not linalg.svd) to calculate a solution to the SVD of $A = \begin{bmatrix}1 & -1\\3 & 1\end{bmatrix}$. You will need to use linalg.eig.

# 1

A = U * Delta  * V$^T$

A is a n x m matrix.

U is an orthogonal n x n matrix.

V is an orthonal m x m matrix.

Delta is a n x m diagonal matrix. It's diagonal elements are the square root of the eigenvalues of V.

# 2

U = AA$^T$

V = A$^T$A

They both have the same eigenvalues.

U and V are orthogonal, Delta is diagonal.

V columns are eigenvectors of A$^T$A, U columns are eigenvectors of AA$^T$.

In [3]:
# 3

import numpy as np

A = np.asarray([[1,-1],[3,1]])

U = A.dot(A.T)
V = A.T.dot(A)

eigen_values = np.linalg.eig(U)

print(eigen_values)

(array([  1.52786405,  10.47213595]), array([[-0.97324899, -0.22975292],
       [ 0.22975292, -0.97324899]]))


In [15]:
D = np.asarray([[(eigen_values[0][0])**1/2,0], [0,(eigen_values[0][1])**1/2]])

In [16]:
D

array([[ 0.76393202,  0.        ],
       [ 0.        ,  5.23606798]])

In [17]:
SVD = U.dot(D.dot(V.T))

In [18]:
SVD

array([[  36.22291236,   24.        ],
       [ 120.        ,  107.77708764]])