# DSCI 6001 5.1.Lab

## QR Factorization

So far you have already learned the $LU$ decomposition/factorization, which was by far the most common method of obtaining a solution to a linear system for some time, until the *Francis method* of $QR$ decomposition came about in the 60's. The Francis method $QR$ decomposition not only gives the eigenvectors to a matrix, but the eigenvalues and the solution to the system as well. $LU$ is still the most common method for decomposing small matrices as it's somewhat faster, but less stable. 

Shortly after this, methods involving *Givens rotations* and *Householder reflections* came about (better stability). The latter method is the best for larger matrices. For very large matrices only approximate methods are possible even today due to the high order ( $O(N^{3})$ ) of all of these algorithms. 

### Concepts

It is a **theorem** that *any nonsingular (invertible) matrix can be factored into a product of two matrices*: A matrix $Q$ of orthogonal vectors (representing an image-preserving map), and an upper-right triangular matrix $R$ much like the $U$ matrix of the $LU$ factorization. From this we may obtain a unique solution to the system.

#### Factoring noninvertible matrices (?!?!) 

So far all your effort (and for the rest of this class) has been bent on factoring invertible or nonsingular matrices. It may seem perhaps that there are at least as many examples of noninvertible or singular matrices that might need to be factored. 

In this case, matrix factorization proceeds by a **least-squares** algorithm. This will be covered somewhat later. Least-squares methods are what are used in industry to provide matrix factorizations at scale.


## Construction of the QR factorization

Let us describe a square **matrix, A**:

$$ {\bf{A}} = \{\vec{a_{,1}}, \vec{a_{,2}}, \vec{a_{,3}}, \cdots, \vec{a_{,n}}\}$$

Now let us apply the Gram-Schmidt process to the columns of ${\bf{A}}$, to obtain a new set of orthonormal column vectors. These vectors describe an orthornormal projection of the image space of the original ${\bf{A}}$:

$$q_1 = \dfrac{u_{,1}}{\|u_{,1}\|}; u_{,1} = a_{,1}$$

$$q_2 =  \dfrac{u_{,2}}{\|u_{,2}\|}; u_{,2} = a_{,2}-(a_{,2} \cdot u_{,1}) u_{,1}$$

$$q_3 = \dfrac{u_{,3}}{\|u_{,3}\|}; u_{,3} = a_{,3}-(a_{,3} \cdot u_{,2}) u_{,2} -(a_{,3} \cdot u_{,1}) u_{,1}$$

$$\vdots$$

$$q_{k+1} = \dfrac{u_{,k+1}}{\|u_{,k+1}\|}; u_{,k+1} = a_{,k+1} - \sum_{n=1}^{k}(a_{,k+1} \cdot u_{,n})u_{,n}$$

And hence form the $N$ columns of the matrix ${\bf{Q}}$:

$${\bf{Q}} = \begin{bmatrix} \vec{q_1} & \vec{q_2} & \cdots & \vec{q_{N}}\end{bmatrix}$$

Now it so turns out that this happens to be a decomposition of ${\bf{A}}$ if we realize that we can dot the rows of ${\bf{Q}}$ with another matrix if we want to simply return the elements of ${\bf{A}}$:

$$\begin{bmatrix} a_{1,1} & a_{1,2} & \cdots & a_{1,N}\\ a_{2,1} & a_{2,2} & \cdots & a_{2,N}\\ \cdots & \cdots & \cdots & \cdots \\ a_{N,1} & a_{M,2} & \cdots & a_{N,N}
\end{bmatrix} = \begin{bmatrix} q_{1,1} & q_{1,2} & \cdots & q_{1,N}\\ q_{2,1} & q_{2,2} & \cdots & q_{2,N}\\ \cdots & \cdots & \cdots & \cdots \\ q_{M,1} & q_{M,2} & \cdots & q_{M,N}
\end{bmatrix}\begin{bmatrix} q_{1,1}a_{1,1} & q_{1,2}a_{1,2} & \cdots & q_{1,N}a_{1,N}\\ 0 & q_{2,2}a_{2,2} & \cdots & q_{2,N}a_{2,N}\\ 0 & 0 & \cdots & \cdots \\ 0 & 0 & 0 & q_{N,N}a_{N,N}
\end{bmatrix} $$

Thus:

$${\bf{Q}} = \begin{bmatrix} | & | & |\\
                             q_{,1} & q_{,2} & q_{,3} \\  
                             | & | & | \end{bmatrix}$$

$${\bf{R}} = \begin{bmatrix} a_{,1} \cdot q_{,1} & a_{,2} \cdot q_{,1} & a_{,3} \cdot q_{,1} \\
                             0 & a_{,2} \cdot q_{,2} & a_{,3} \cdot q_{,2}  \\  
                             0 & 0 & a_{,3} \cdot q_{,3} \end{bmatrix}$$

This is because each element of ${\bf{Q}}$ contains the magnitude of the dot product, thus the inner product of each row by column results in the appropriate element of ${\bf{A}}$.


### Example:

Compute the QR factorization for the matrix using Gramm-Schmidt:

$$\begin{bmatrix} 1 & 1 & 0 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix}$$


$$ \vec{u^{(1)}} = \vec{a^{(1)}}$$
$$\vec{q_{,1}} =\dfrac{u_{,1}}{\|u_{,1}\|} = \dfrac{1}{\sqrt{2}}\begin{bmatrix}1\\1\\0\end{bmatrix}$$

$$ \vec{u_{,2}} = a_{,2}-(a_{,2} \cdot u_{,1}) u_{,1} = \begin{bmatrix}1\\0\\1\end{bmatrix} - \dfrac{1}{\sqrt{2}}\begin{bmatrix}\dfrac{1}{\sqrt{2}}\\\dfrac{1}{\sqrt{2}}\\0\end{bmatrix} =  \begin{bmatrix}\dfrac{1}{2}\\-\dfrac{1}{2}\\1\end{bmatrix}$$

$$\vec{q_{,2}} = \dfrac{u_{,2}}{\|u_{,2}\|} = \begin{bmatrix}\dfrac{1}{\sqrt{6}}\\-\dfrac{1}{\sqrt{6}}\\ \dfrac{2}{\sqrt{6}}\end{bmatrix}$$

$$ \vec{u_{,3}} = a_{,3}-(a_{,3} \cdot u_{,2}) u_{,2}-(a_{,3} \cdot u_{,1}) u_{,1} $$

$$ \vec{u_{,3}} = \begin{bmatrix}0\\1\\1\end{bmatrix} -\dfrac{1}{\sqrt{6}}\begin{bmatrix}\dfrac{1}{\sqrt{6}}\\-\dfrac{1}{\sqrt{6}}\\ \dfrac{2}{\sqrt{6}}\end{bmatrix} - \dfrac{1}{\sqrt{2}}\begin{bmatrix}\dfrac{1}{\sqrt{2}}\\\dfrac{1}{\sqrt{2}}\\0\end{bmatrix} = \begin{bmatrix}-\dfrac{1}{\sqrt{3}}\\\dfrac{1}{\sqrt{3}}\\ \dfrac{1}{\sqrt{3}}\end{bmatrix}$$

Thus we have a full basis for the image space of $\bf{Q}$:

$$\left\{ \begin{bmatrix}\dfrac{1}{\sqrt{2}} \\ \dfrac{1}{\sqrt{2}}\\0 \end{bmatrix}, \begin{bmatrix}\dfrac{1}{\sqrt{6}}\\-\dfrac{1}{\sqrt{6}}\\ \dfrac{2}{\sqrt{6}}\end{bmatrix}, \begin{bmatrix}-\dfrac{1}{\sqrt{3}}\\\dfrac{1}{\sqrt{3}}\\ \dfrac{1}{\sqrt{3}}\end{bmatrix}  \right\}$$

Now we can construct Q confidently:

$${\bf{Q}} = \begin{bmatrix}\dfrac{1}{\sqrt{2}} & \dfrac{1}{\sqrt{6}} & -\dfrac{1}{\sqrt{3}} \\ \dfrac{1}{\sqrt{2}} & -\dfrac{1}{\sqrt{6}} & \dfrac{1}{\sqrt{3}} \\ 0 & \dfrac{2}{\sqrt{6}} & \dfrac{1}{\sqrt{3}} \end{bmatrix}$$

And R follows simply with elements that are the proscribed dot products:

$${\bf{R}} = \begin{bmatrix}\dfrac{\sqrt{2}}{2} & \dfrac{1}{\sqrt{3}} & \dfrac{1}{\sqrt{2}} \\ 0 & \dfrac{3}{\sqrt{6}} & \dfrac{1}{\sqrt{6}} \\ 0 & 0 & \dfrac{2}{\sqrt{3}} \end{bmatrix}$$

### QUIZ:

Satisfy yourself that this is true.


In [32]:
import numpy as np
import numpy.linalg as LA
from math import copysign, hypot

A = np.array([[1, 1, 0 ],[1, 0, 1],[0, 1, 1]])

print(A)

(l, Q) = LA.eig(A)
print(Q)


[[1 1 0]
 [1 0 1]
 [0 1 1]]
[[  4.08248290e-01   7.07106781e-01   5.77350269e-01]
 [ -8.16496581e-01   1.19612948e-17   5.77350269e-01]
 [  4.08248290e-01  -7.07106781e-01   5.77350269e-01]]


## Task 1: 

Use the Gramm-Schmidt algorithm (by hand) to produce the QR factorization of the following matrix:

$$ A = \begin{bmatrix} -2 & 0 & 1\\ 1 & -2 & 1 \\ 1 & -1 & 0\end{bmatrix}$$

Show most of your steps. You may use the computer to check your steps.

u${1} = [-2,1,1]^T$, but we need to normalize the vector: the norm of [-2,1,1]$^T$ is $\sqrt6$, so 

u${1} = \frac{1}{\sqrt6} * [-2,1,1]^T$

u${2} = [0,-2,-1]^T - ([0,-2,-1]^T * \frac{1}{\sqrt6} * [-2,1,1]^T) * \frac{1}{\sqrt6} * [-2,1,1]^T = [0,-2,-1]^T - \frac{1}{3} * [-2,1,1]^T = [0,-2,-1]^T + [-1,1/2,1/2]^T = [-1,-3/2,-1/2]^T$

In [12]:
import numpy as np

u_1 = np.asarray([-2,1,1])
u_1 = u_1.reshape(3,1)
u_1 = u_1/(u_1.T.dot(u_1))
u_1

array([[-0.33333333],
       [ 0.16666667],
       [ 0.16666667]])

In [13]:
a_2 = np.asarray([0,-2,-1])
a_2 = a_2.reshape(3,1)
u_2 = a_2 - (u_1.T.dot(a_2)/u_1.T.dot(u_1)) * u_1
u_2 = u_2/(u_2.T.dot(u_2))
u_2

array([[-0.28571429],
       [-0.42857143],
       [-0.14285714]])

u${3} = [1,1,0]^T - ([1,1,0]^T * \sqrt(\frac{2}{7}) * [-1,-3/2,-1/2]^T) * \sqrt(\frac{2}{7}) * [-1,-3/2,-1/2]^T - ([1,1,0]^T * \frac{1}{\sqrt6} * [-2,1,1]^T) * \frac{1}{\sqrt6} * [-2,1,1]^T$

In [17]:
a_3 = np.asarray([1,1,0])
a_3 = a_3.reshape(3,1)
u_3 = a_3 - ((u_1.T.dot(a_3)/u_1.T.dot(u_1)) * u_1) - ((u_2.T.dot(a_3)/u_2.T.dot(u_2)) * u_2)
u_3 = u_3/(u_3.T.dot(u_3))
u_3

array([[-1.],
       [ 2.],
       [-4.]])

In [18]:
u_1.T.dot(u_2)

array([[ -6.93889390e-18]])

In [19]:
u_1.T.dot(u_3)

array([[ -2.66453526e-15]])

In [34]:
Q = [list(u_1.T),list(u_2.T),list(u_3.T)]
Q = np.asarray(Q)
Q = Q.reshape(3,3)
Q = Q.T
Q

array([[-0.33333333, -0.28571429, -1.        ],
       [ 0.16666667, -0.42857143,  2.        ],
       [ 0.16666667, -0.14285714, -4.        ]])

In [32]:
A = np.asarray([-2,0,1,1,-2,1,-1,1,0])
A = A.reshape(3,3)
A

array([[-2,  0,  1],
       [ 1, -2,  1],
       [-1,  1,  0]])

In [33]:
A.dot(Q)

array([[ 0.83333333,  0.42857143, -2.        ],
       [-0.5       ,  0.42857143, -9.        ],
       [ 0.5       , -0.14285714,  3.        ]])

## Task 2:

Write the Gram-Schmidt algorithm using the code stub below. You may also write your own GS algorithm if you want to pursue more optimized strategies. There are a number of ways that the GS can be written using broadcasting or matrix-based strategies. Tomorrow, we will write the modified GS algorithm that actually ends up being much simpler to implement than the below strategy.

Here we actually store the current state of the GS basis in a matrix $Q$ just as if we were writing it by hand. As we build up the GS basis, we iterate through each of the vectors, calculating the projection of the $Q$ vectors $v$ onto each of the input vectors $u$. Then we subtract these projections from the current vector taken from the original set. After normalization, we have our new orthonormal vector that we can add into Q. The algorithm continues on until we have orthonormalized every vector in $A$. 

In [47]:
import numpy as np
def gram_schmidt(A, col_vecs=True, norm=True):
    # assumes column vector format of X
    
    # you may want to check the determinant (why?)
    
    
    # Initialize an empty matrix to store the current state of the GS basis of Q
    
    # flip the matrix to make the code easier to read
    # Easy to process is A is converted into a list

    
    # * for each vector u in At (the column matrix) for j, col in enumerate(At)
    
        #np.dot(u,v)
        
        # * for each of the other vectors v in Q
        
            # you may need to cast v into the extra dimensions, cast into numpy here:
            # v = expand_dims(rowofQ, axis=0)
            
            # * remove proj_v(u) from u => u-(v.u/v.v)*v
            
        # * normalize u => np.linalg.norm
    
        # you'll need to add the new u to your Q matrix => set Q as list, then:
        # Q.append(u.flatten())
        #Q.append(u.flatten())
    
    # * return the Q matrix

In [54]:
import numpy as np
def gram_schmidt(A, col_vecs=True, norm=True):
    
    if(np.linalg.det(A) != 0):
    
        Q = []
    
        # Easy to process is A is converted into a list.
        # First, we transpose A, so the columns are rows.
        A = list(A.T)

        # We iterate through rows.
        for x in A:
            # The current row is a vector.
            u = x
            # We iterate through Q to calculate the projections and substract them from current row.
            for y in Q:
                u = u - (u.dot(y)/y.dot(y))* y
        
            # We normalize the vector.
            u = u/np.linalg.norm(u)
            # We append the normalized vector to the list.
            Q.append(u)

        # We return th list Q as an numpy array.
        return np.asarray(Q)
    else:
        print("Determinant of", A, "is 0.")

In [55]:
# Quick test harness

A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])
Q = gram_schmidt(A)
R = Q.dot(A)

R = Q.T.dot(A)
print(Q)
print(Q.dot(R))

[[-0.81649658  0.40824829  0.40824829]
 [-0.53452248 -0.80178373 -0.26726124]
 [-0.21821789  0.43643578 -0.87287156]]
[[ -2.00000000e+00  -1.77509978e-16   1.00000000e+00]
 [  1.00000000e+00  -2.00000000e+00   1.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00  -5.90605253e-16]]


In [185]:
# Quick test harness

A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])
Q = gram_schmidt(A)
R = Q.dot(A)

R = Q.T.dot(A)
print(Q)
print(Q.dot(R))


[[-0.81649658 -0.53452248 -0.21821789]
 [ 0.40824829 -0.80178373  0.43643578]
 [ 0.40824829 -0.26726124 -0.87287156]]
[[ -2.00000000e+00   2.67810419e-16   1.00000000e+00]
 [  1.00000000e+00  -2.00000000e+00   1.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00  -5.82867088e-16]]


In [151]:
A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])

gram_schmidt_rows(A.T)



[[-0.81649658  0.40824829  0.40824829]
 [-0.53452248 -0.80178373 -0.26726124]
 [-0.21821789  0.43643578 -0.87287156]]
