# RAT 5.1

Let $L$ be a linear transformation from $R^{3}$ into $R^{2}$ such that $L(e_{1}) = \begin{bmatrix}-1\\ 6\end{bmatrix}$, $L(e_{2}) = \begin{bmatrix}0\\ 2\end{bmatrix}$, $L(e_{3}) = \begin{bmatrix}8\\ 1\end{bmatrix}$.

1. Find a matrix $A$ such that $L(\bf{x}) = A\bf{x}$
2. (Extra) find the equation of the plane $L$ maps to.

In [3]:
import numpy as np
e_1 = np.asarray([-1,6])
e_2 = np.asarray([0,2])
e_3 = np.asarray([8,1])
e_1 = e_1.reshape(2,1)
e_2 = e_2.reshape(2,1)
e_3 = e_3.reshape(2,1)

In [4]:
e_1.T.dot(e_2)

array([[12]])

In [5]:
e_2.T.dot(e_3)

array([[2]])

In [6]:
# They are not lineraly independent.

In [7]:
e_2_orth = e_2 - (e_1.T.dot(e_2)/e_1.T.dot(e_1)) * e_1

In [8]:
e_2_orth

array([[ 0.32432432],
       [ 0.05405405]])

In [9]:
e_1.T.dot(e_2_orth)

array([[ -6.66133815e-16]])

In [11]:
e_3_orth = e_3 - ((e_1.T.dot(e_3)/e_1.T.dot(e_1)) * e_1) - ((e_2_orth.T.dot(e_3)/e_2_orth.T.dot(e_2_orth)) * e_2_orth)

In [12]:
e_1.T.dot(e_3_orth)

array([[  1.68753900e-14]])

In [14]:
A = np.asarray([e_1,e_2_orth, e_3_orth])
A = A.reshape(3,2)
A

array([[ -1.00000000e+00,   6.00000000e+00],
       [  3.24324324e-01,   5.40540541e-02],
       [ -8.88178420e-16,   2.66453526e-15]])