# DSCI6001 4.4 Lab  

## Recursive calculation of the determinant

(This is a graded lab assignment)

Today you will calculate the determinant recursively using the skills you developed yesterday. You should be familiar enough to jump into writing the algorithm essentially from scratch. 

The determinant is easily calculated using the Laplace expansion:

$$det(A) = \sum_{i=1}^{N} (-1)^{i+1} A_{i,1} det(C_{i})$$

where $C_{i,1}$ is the $(n-1) \times (n-1)$ matrix obtained from A by removing (deleting) the i-th row and first column. (The first column does not play a special role here: the determinant remains the same if we use any other column.) 

Note that the stopping condition in this case for the determinant function is the determinant of size $2 \times 2$. Yes, you can consider expansions that end in the $1 \times 1$ expansion. Just make sure your math is right. 

Your code should be able to pass the simple test harness provided below.
Our solution was written in 11 lines. You might consider making use of the `numpy.delete` function (make sure to test it out to understand it). Our other comment is to take advantage of simple sums where you can. Remember that each determinant is a sum over columns !!!

In [104]:
def det(x):
    
    # you might consider making a `minor` function to help you calculate the minor matrices 
    def minor(x, i, j):
        pass
    
    # recursion goes here. You'll need to define the base case first!! In every other case, 
    # you're returning a sum!
    
    pass

In [104]:
def det(x, sum_of_minors = None):
    
    if sum_of_minors == None:
        sum_of_minors = []
        
    i = x.shape[0]-1
    j = x.shape[1]-1
    
    # you might consider making a `minor` function to help you calculate the minor matrices 
    def minor(x, i, j):
        
        # Delete current column:
        x = np.delete(x, j, axis=1)
        # Delete 1st row (remember, index starts at 0 for 1st element)::
        x = np.delete(x, 0, axis=0)
        return x
    
    # recursion goes here. You'll need to define the base case first!! In every other case, 
    # you're returning a sum!
    
    # Base case:
    if x.shape == (2,2):
        # Be careful with indexing for a_11, a_12, a_21, a_22.
        #return sum_of_minors.append(x[0,0] * x[1,1] - x[0,1] * x[1,0])
        sum_of_minors.append(x[0,0] * x[1,1] - x[0,1] * x[1,0])
    else:
        for s in range(i):
            factor = ((-1)**(s+2)) * x[0,s]
            sum_of_minors = det(factor * minor(x,i,j), sum_of_minors)
        
    return sum(sum_of_minors)

In [105]:
# Here is a simple test harness

import numpy as np
import copy
import numpy.linalg as LA
    
for i in range(20):
    X = np.random.randint(5, size=(6,6))
    #assert np.isclose(float(det(X)), LA.det(X))
    assert np.isclose(float(det(X,0)), LA.det(X,0))

AttributeError: 'int' object has no attribute 'append'

In [102]:
np.random.randint(5, size=(6,6))

array([[4, 1, 2, 3, 4, 1],
       [2, 3, 1, 0, 4, 1],
       [1, 4, 3, 4, 3, 0],
       [4, 4, 3, 4, 2, 2],
       [0, 2, 0, 2, 4, 2],
       [0, 1, 1, 4, 0, 4]])

In [1]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [12]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr = np.delete(arr, 0,1)

In [14]:
arr

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [15]:
arr = np.delete(arr, 2,0)

In [16]:
arr

array([[2, 3, 4],
       [6, 7, 8]])