# DSCI 6001 4.4 Lecture

##By the end of this lecture you will be:
1. More familiar with rotation matrices



##Rotations

Consider the rotation of a vector or matrix in $R^2$. Suppose a nonzero vector ${\bf u} = [u_1~~u_2]$ is rotated counterclockwise through an angle $\theta$ to produce ${\bf v} = [v_1~~v_2]$. 

Using the fact that $\| {\bf u} \| = \| {\bf v} \| = v$,

$$v_1 = v \cos (\phi + \theta) = v (\cos \theta \cos \phi - \sin \theta \sin \phi)$$
$$v_2 = v \sin (\phi + \theta) = v (\sin \theta \cos \phi - \cos \theta \sin \phi)$$

Described in the below diagram

![](images/rotation-2d.png)


Substituting $\cos \phi = u_1/v$ and $\sin \phi = u_2/v$ yields

$$v_1 = u_1 \cos \theta - u_2 \sin \theta$$
$$v_2 = u_1 \sin \theta + u_2 \cos \theta$$

In matrix form:

$$\left[ \begin{matrix} v_1 \\ v_2 \end{matrix} \right] = \left[ \begin{matrix} \cos \theta & -\sin \theta \\ \sin \theta & \cos \theta \end{matrix} \right] \left[ \begin{matrix} u_1 \\ u_2 \end{matrix} \right] $$

In other words, ${\bf v} = {\bf P u}$, where $\bf P$ is called the _rotation matrix_ or rotator. Notice that $\bf P$ is an orthogonal matrix because ${\bf P}^T {\bf P} = {\bf I}.$ This means that if ${\bf v} = {\bf P u}$, then ${\bf u} = {\bf P}^T {\bf v}$. If $\bf P$ rotates a vector through an angle $\theta$, the ${\bf P}^T$ rotates then vector through an angle $\theta$.


##Rotations in $\mathbb{R}^3$

Rotating vectors in $R^3$ around any one of the coordinate axes is similar. Suppose that ${\bf v} = \begin{bmatrix}v_1\\v_2\\v_3\end{bmatrix}$ is obained by rotating ${\bf u} = \begin{bmatrix}u_1\\u_2\\u_3\end{bmatrix}$ counterclockwise through an angle $\theta$ around the $z$-axis. In this case, the third coordinate remains unaffected, i.e., $v_3 = u_3$. 

Now, consider the projection of $\bf u$ onto $xy$-plane, ${\bf u}_p = [u_1~~u_2~~0]$. As $\bf u$ is rotated around $z$-axis by angle $\theta$, the projection ${\bf u}_p$ gets rotated around the origin by the same angle. Thus the problem is reduced to rotation in the $xy$-plane, and we already know how to do this. Therefore, this rotation can be expressed as


$$\left[ \begin{matrix} v_1 \\ v_2 \\ v_3 \end{matrix} \right] = \left[ \begin{matrix} \cos \theta & -\sin \theta & 0 \\ \sin \theta & \cos \theta & 0 \\ 0 & 0 & 1 \end{matrix} \right] \left[ \begin{matrix} u_1 \\ u_2 \\ u_3 \end{matrix} \right] $$

$${\bf v} = {\bf P}_z {\bf u}$$

So, ${\bf P}_z$ is the matrix that rotates vectors in $R^3$ counterclockwise aroung the $z$-axis through an angle $\theta$. It is easy to verity that ${\bf P}_z$ is on orthogonal matrix. Using similar arguments, we can derive orthogonal matrices that rotate vectors around the $x$-axis or aroung the $y$-axis.



###Standard rotation matrices in $\mathbb{R}^3$

${\bf P}_x = \left[ \begin{matrix} 1 & 0 & 0 \\ 0 & \cos \theta & -\sin \theta  \\ 0 & \sin \theta & \cos \theta  \end{matrix} \right]$

${\bf P}_y = \left[ \begin{matrix} \cos \theta & 0&  -\sin \theta \\ 0 & 1 & 0 \\ \sin \theta & 0 & \cos \theta  \end{matrix} \right]$

${\bf P}_z = \left[ \begin{matrix} \cos \theta & -\sin \theta & 0 \\ \sin \theta & \cos \theta & 0 \\ 0 & 0 & 1 \end{matrix} \right]$

**Rotations in higher dimensions** are straightforward generalizations of rotations in $R^3$. **Any $n \times n$ orthogonal matrix rotation** preserves the dimensionality of a $n$-dim matrix. and thus is thought of as a rotation in $R^n$.

The principal property of rotations beyond the preservation of spatial relationships is that they always have an axis of rotation: meaning there is always one line in $R^n$ that is left undisturbed by the rotation. 

Given an arbitrary rotation matrix ${\bf P}$, one can find the axis of rotation by solving the following equation:

${\bf P x} = \lambda {\bf x}$, $\lambda = 1$

Hence we want to find an eigenvector ${\bf x}$ of $\bf P$ with eigenvalue 1. Once we find such a vector, then we’ll have the corresponding axis of rotation. These two properties are synonymous and is a logical extension of the meaning of eigenvectors, which has been talked about extensively so far.

####Orthogonal Diagonalization and Rotation

If $\bf A$ is a symmetric (or a NORMAL i.e. ${\bf AA^T = A^TA}$) matrix, then it is orthogonally diagonalizable:

$${\bf A} = {\bf PDP}^T$$

Here the matrix $\bf P$ is orthogonal, which means, for any vector $\bf w$, $\|{\bf Pw} \| = \|{\bf w}\|$. Therefore ${\bf P}$ is a matrix of rotation.

For an eigenvector ${\bf x}$ of matrix $\bf A$:

$${\bf Ax} = {\bf PDP}^T {\bf x}$$

The application of ${\bf PDP}^T$ on $\bf x$ can be described geometrically in the following way:

In [ ]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#define a drawer.
def draw_vec(v, col='r', ls ='solid'):
    plt.arrow(0,0,v[0][0],v[1][0], head_width=0.05, head_length=0.05, ec=col, ls=ls);
    plt.xlim(-0.2,3.2)
    plt.ylim(-0.2,3.2)

In [ ]:
A = np.array([[2,1],[1,2]])
#A = np.array([[3,2],[1,4]])

print 'consider the matrix A:\n',A

ev, P = np.linalg.eig(A)
print 'eigenvalues:\n',ev
print 'eigenvectors:\n', P

v1 = np.array([[.25],[1]])
D = np.diag(ev)

In [ ]:
print "draw v1"
print v1

draw_vec(v1,'b')

In [ ]:
v2 = A.dot(v1)
print 'Now draw draw the product of matrix A on v1 as GREEN'

draw_vec(v1,'b')
draw_vec(v2,'g', ls = 'dashdot')

In [ ]:
print 'Now look at how P^T rotates v1:'

draw_vec(v1,'b')
draw_vec(v2,'g', ls = 'dashdot')

draw_vec(P.T.dot(v1))

In [ ]:
print 'Now D scales the rotated eigenvector:'
draw_vec(v1,'b')
draw_vec(v2,'g', ls = 'dashdot')

draw_vec(D.dot(P.T.dot(v1)))

In [ ]:
print 'and P rotates the scaled vector back onto the GREEN image vector:'
draw_vec(v1,'b')

draw_vec(P.dot(D.dot(P.T.dot(v1))))
draw_vec(v2,'g', ls = 'dashdot')


##Assigned Problems:

1) Perform the following sequence of rotations in $R^3$ beginning with

$${\bf v}_0 = \begin{bmatrix} 1 \\ 1 \\ -1 \end{bmatrix}$$

1. Rotate ${\bf v}_0$ counterclockwise $45^\circ$ around the $x$-axis to produce ${\bf v}_1$.

2. Rotate ${\bf v}_1$ clockwise $90^\circ$ around the $y$-axis to produce ${\bf v}_2$.

3.  Rotate ${\bf v}_2$ counterclockwise $30^\circ$ around the $z$-axis to produce ${\bf v}_3$.

2) Verify that the matrix ${\bf P}_y$ is orthogonal.

3) Diagonalize the following symmetric matrix

$${\bf A} = \begin{bmatrix} 3 & 1/2 \\ 1/2 & 2 \end{bmatrix}$$

(a) Plot the effect of $\bf A$ on the vectors $\begin{bmatrix}1\\0\end{bmatrix}$, $\begin{bmatrix}1\\1\end{bmatrix}$ and $\begin{bmatrix}0\\1\end{bmatrix}$. 

(b) Plot the effect of ${\bf P}^T$, ${\bf DP}^T$ and ${\bf PDP}^T$ on the same vectors

In [8]:
import numpy as np

v_0 = np.asarray([1,1,-1])
v_0 = v.reshape(3,1)
v_0

array([[ 1],
       [ 1],
       [-1]])

In [9]:
P_x = np.asarray([1,0,0,0,np.cos(45),-np.sin(45),0,np.sin(45),np.cos(45)])
P_x = P_x.reshape(3,3)
P_x

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.52532199, -0.85090352],
       [ 0.        ,  0.85090352,  0.52532199]])

In [10]:
v_1 = P_x.dot(v_0)
v_1

array([[ 1.        ],
       [ 1.37622551],
       [ 0.32558154]])

In [11]:
P_y = np.asarray([np.cos(-90),0,-np.sin(-90),0,1,0,np.sin(-90),0,np.cos(-90)])
P_y = P_y.reshape(3,3)
P_y

array([[-0.44807362,  0.        ,  0.89399666],
       [ 0.        ,  1.        ,  0.        ],
       [-0.89399666,  0.        , -0.44807362]])

In [12]:
v_2 = P_y.dot(v_1)
v_2

array([[-0.15700481],
       [ 1.37622551],
       [-1.03988116]])

In [14]:
P_z = np.asarray([np.cos(30),-np.sin(30),0,np.sin(30),np.cos(30),0,0,0,1])
P_z = P_z.reshape(3,3)
P_z

array([[ 0.15425145,  0.98803162,  0.        ],
       [-0.98803162,  0.15425145,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [15]:
v_3 = P_z.dot(v_2)
v_3

array([[ 1.33553611],
       [ 0.3674105 ],
       [-1.03988116]])