# RAT 4.4

Orthonormalize $\vec{v_{1}} = \begin{bmatrix}1, -2, 1\end{bmatrix}$, $\vec{v_{2}} = \begin{bmatrix}1, 1, 0\end{bmatrix}$, $\vec{v_{3}} = \begin{bmatrix}0, -1, -1\end{bmatrix}$

In [1]:
import numpy as np

In [2]:
v1 = np.asarray([[1],[-2],[1]])

In [3]:
v2 = np.asarray([[1],[1],[0]])

In [4]:
v3 = np.asarray([[0],[-1],[-1]])

In [5]:
v1.T.dot(v2)

array([[-1]])

In [7]:
v1.T.dot(v3)

array([[1]])

In [8]:
v2.T.dot(v3)

array([[-1]])

In [6]:
# We use v1 as basis to construct the rest of vectors.

In [11]:
v2_orth = v2 - (v1.T.dot(v2)/v1.T.dot(v1)) * v1

In [12]:
v2_orth

array([[ 1.16666667],
       [ 0.66666667],
       [ 0.16666667]])

In [36]:
v3_orth = v3 - ((v1.T.dot(v3)/v1.T.dot(v1)) * v3) - ((v2_orth.T.dot(v3)/v2_orth.T.dot(v2_orth)) * v3)

In [37]:
v3_orth

array([[ 0.        ],
       [-1.28787879],
       [-1.28787879]])

In [38]:
v1.T.dot(v2_orth)

array([[ -8.32667268e-17]])

In [39]:
v1.T.dot(v3_orth)

array([[ 1.28787879]])