In [1]:
import numpy as np

In [8]:
# 11
A = [[3,1,-3],[1,4,2],[-3,2,5]]
B = [[0,4,1],[-4,0,2],[-1,2,0]]
u = [[2],[0],[-5]]

In [12]:
A = np.asarray(A)
B = np.asarray(B)
u = np.asarray(u)

A.dot(B)

array([[ -1,   6,   5],
       [-18,   8,   9],
       [-13,  -2,   1]])

In [13]:
B.dot(A)

array([[  1,  18,  13],
       [-18,   0,  22],
       [ -1,   7,   7]])

In [19]:
# 13
A.dot(u)

array([[ 21],
       [ -8],
       [-31]])

In [20]:
(u.T).dot(A)

array([[ 21,  -8, -31]])

In [18]:
# 17
np.linalg.det(A)

-5.0000000000000062

In [22]:
np.linalg.det(A.dot(A))

25.000000000000238

In [24]:
(np.linalg.det(A))**2

25.00000000000006

In [25]:
np.linalg.det(B)

-15.999999999999998

In [34]:
# 20
C = np.multiply(B,-1)
np.add(A,A.T).dot(np.add(B,C.T))

array([[ -4,  48,  12],
       [-72,  16,   4],
       [-52, -48, -12]])

In [42]:
# 24
A1 = [[-6,39,-9],[2,-13,3]]
B1 = [-12,-4]

A1 = np.asarray(A1)
B1 = np.asarray(B1)

try:
    print(np.linalg.solve(A1,B1))
except:
    print('Cannot solve linear system.')

Cannot solve linear system.


In [43]:
# 25
C1 = [[0.3,-0.7,1.3],[0,0.9,-0.8],[0,0,0.7]]
D1 = [3.24,-2.53,1.19]

C1 = np.asarray(C1)
D1 = np.asarray(D1)

try:
    print(np.linalg.solve(C1,D1))
except:
    print('Cannot solve linear system.')

[ 0.4 -1.3  1.7]


In [44]:
# 26
E1 = [[2,3,-7],[-4,-6,14]]
F1 = [3,7]

E1 = np.asarray(E1)
F1 = np.asarray(F1)

try:
    print(np.linalg.solve(E1,F1))
except:
    print('Cannot solve linear system.')

Cannot solve linear system.


In [50]:
# 30
G1 = [[-6,39,-9],[2,-13,3],[-12,4]]

G1 = np.asarray(G1)

# A1 is coefficient matrix, G1 is augmented matrix.
np.rank(A1), np.rank(G1)

//anaconda/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)


(2, 1)

In [53]:
# 33

# One node:
# i1 - i2 - i3 = 0

# Another node:
# -i1 + i2 + i3 = 0

# Top loop:
# - 10i2 + 20i3= 0

# Bottom loop:
# 10(i1 + i2) = 110

a = np.asarray([[1,-1,-1],[-1,1,1],[0,-10,20],[10,10,0]])
b = np.asarray([0,0,0,110])
               
try:
    print(np.linalg.solve(a,b))
except:
    print('Cannot solve linear system.')

Cannot solve linear system.


In [54]:
# 35

# One node:
# i1 + i3 = 0

# Another node:
# - i2 + i3 = 0

# Top loop:
# 10i1 - 30i3 = 10

# Botton loop:
# 20i2 + 30i3 = 130

c = np.asarray([[1,0,1],[0,-1,1],[10,0,-30],[0,20,30]])
d = np.asarray([0,0,10,130])
               
try:
    print(np.linalg.solve(c,d))
except:
    print('Cannot solve linear system.')

Cannot solve linear system.
